import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/dist/client/link";
import { SiDirectus, SiOpensearch, SiPostgresql, SiReactrouter } from "react-icons/si";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col bg-slate-950 text-slate-100 font-sans">
        <header className="sticky top-0 z-40 w-full backdrop-blur-md bg-slate-950/70 border-b border-slate-800">
          <div className="container mx-auto px-4 h-16 flex items-center justify-between">
            <div className="font-bold text-xl tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-indigo-400">
              Directus OpenSearch Demo
            </div>
            <div className="flex gap-4">
              <Link
                href="/learn_directus"
                className="transition-colors bg-transparent hover:bg-gradient-to-r from-blue-700 to-violet-700 border rounded-md p-2 border-slate-200 "
              >
                <SiDirectus className="inline-block mr-2" />
                 Directus
              </Link>
              <Link
                href="/learn_opensearch"
                className="transition-colors bg-transparent hover:bg-gradient-to-r from-blue-700 to-violet-700 border rounded-md p-2 border-slate-200 "
              >
                <SiOpensearch className="inline-block mr-2" />
                 OpenSearch
              </Link>
              <Link
                href="/learn_postgresql"
                className="transition-colors bg-transparent hover:bg-gradient-to-r from-blue-700 to-violet-700 border rounded-md p-2 border-slate-200 "
              >
                <SiPostgresql  className="inline-block mr-2" />
                 PostgreSQL
              </Link>
              <Link
                href="/learn_react_router"
                className="transition-colors bg-transparent hover:bg-gradient-to-r from-blue-700 to-violet-700 border rounded-md p-2 border-slate-200 "
              >
                <SiReactrouter   className="inline-block mr-2" />
                 React Router
              </Link>
            </div>
            <nav className="flex gap-6 text-sm font-medium">
              <Link href="/" className="hover:text-blue-400 transition-colors">
                Home
              </Link>
              <Link
                href="/search"
                className="hover:text-blue-400 transition-colors"
              >
                Search
              </Link>
              <Link
                href="/architecture"
                className="hover:text-blue-400 transition-colors"
              >
                Architecture
              </Link>
            </nav>
          </div>
        </header>
        <main className="flex-1 w-full max-w-6xl mx-auto p-6 md:p-10">
          {children}
        </main>
      </body>
    </html>
  );
}
